// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://giephjkzfkuxihkkohrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpZXBoamt6Zmt1eGloa2tvaHJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3NjA0ODYsImV4cCI6MjA1NjMzNjQ4Nn0.XIOzx3C5lD_qYLm7Oesi6XCHJjxyB_oyHddJXj1OG-g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);